### ISSUE TITLE
Code cleaning and formatting 

### ISSUE THREAD

**Issue by Yash-Parsana** [Yash-Parsana/CrazyCoderServerlessApi#10]
You need to improve code quality by cleaning the code and adding proper formatting.

Subtasks:
Remove unnecessary white space comments and code.
Add proper formatting you may use linting tools.

**Comment by Ashwin1902** [comment]
Can I work on this issue?

**Comment by gitshanmukh123** [comment]
CAN I WORK ON THIS ISSUE , I WANT TO SOMEHOW CONTRIBUTE TO THIS PROJECT UNDER GSSOC 2024

**Comment by Yash-Parsana** [comment]
@Ashwin1902  this issue is assigned to you.

**Comment by MrCodYrohit** [comment]
@Ashwin1902  @Yash-Parsana Please assign this issue to me. I am willing to work on this issue and try to fix it ASAP.

**Comment by KushagraKatiha** [comment]
Please assign to me this, I can solve this
