### ISSUE TITLE
Expose route for gfg contest

### ISSUE THREAD

**Issue by Yash-Parsana** [Yash-Parsana/CrazyCoderServerlessApi#11]
You need to expose new route for gfg contests data.

Subtasks :
Find out if gfg provides api for contests data, otherwise you can use web scrapping to get data. 

Make sure response must be in below format.

{
"name": "contest name",
"start_time": timestamp (integer) (eg 1715434800000) ,
"end_time": same format as start time ,
"status": "upcoming or ongoing"
},

Ask doubts in this thread, if you have any.

**Comment by Ishan942** [comment]
Hey I would like to work on this issue can you assign it to me, would probably use web scrapping.

**Comment by kart2004** [comment]
Hi, @Yash-Parsana, there is no gfg api for contests data. Can you assign it to me, I can use web scrapping to get the necessary data.
