### ISSUE TITLE
Expose route for gfg profile data

### ISSUE THREAD

**Issue by Yash-Parsana** [Yash-Parsana/CrazyCoderServerlessApi#12]
You need to expose new route for gfg profile data.

Subtasks :
Find out if gfg provides api for contests data, otherwise you can use web scrapping to get data.

Follow below response format.

{
"status": "success or failure",
"handle": string,
"over_all_coding_score": integer,
"total_problem_solved": integer,
"monthly_coding_score": integer,
"over_all_article_published": integer,
}

Ask doubts in this thread, if you have any.

**Comment by NIKHIL0VERMA** [comment]
Hey @Yash-Parsana,
I did a bit of research and found the unofficial API. I can implement this as soon as you assign this to me.

Best Regards,
**Nikhil Verma**

**Comment by Yash-Parsana** [comment]
Let me check that api, can you share it here? @NIKHIL0VERMA

**Comment by NIKHIL0VERMA** [comment]
ya sure, Here we go https://github.com/arnoob16/GeeksForGeeksAPI

**Comment by GbCderr14** [comment]
Hi @Yash-Parsana  I would like to implement this using scrapping please assign this to me..

**Comment by Yash-Parsana** [comment]
@NIKHIL0VERMA we don't want to keep external dependency for this feature so i suggest you to implement it by web scrapping.
If you want to work on this issue then comment on this thread by today.

**Comment by kart2004** [comment]
Hi @NIKHIL0VERMA. Can you please assign this to me, I can get it done quickly.
Thanks in advance.
