### ISSUE TITLE
Missing Code of Conduct & Contribution.md

### ISSUE THREAD

**Issue by Dhruv-Pattel** [Yash-Parsana/CrazyCoderServerlessApi#13]
This repository has no Code of Conduct & Contribution.md file. any open-source project needs to set clear standards for behavior. It promotes inclusivity, prevents misconduct, fosters accountability, and maintains a positive environment.

Please assign this issue to me.

**Comment by suhanipaliwal** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by Yash-Parsana** [comment]
@Dhruv-Pattel this issue is assigned to you.

**Comment by MrCodYrohit** [comment]
@Yash-Parsana Please assign this isuue to me, i will try to complete it within 24 hrs.

**Comment by aasthakourav20** [comment]
Hey @Dhruv-Pattel , This issue is still open , kindly assign it to me under GSSoC'24
