### ISSUE TITLE
[ADD FEATURE] : filter options in home page

### ISSUE THREAD

**Issue by Sakhi29** [Yash-Parsana/CrazyCoderServerlessApi#14]
We can mention options like latest first or earliest first kind of filters according to time stamps in the home section where all the contests are display for each coding platform.

By doing so, user will be able to sort the data according to which contest is latest upcoming or will be available in the next week or will it be today etc.

Please assign this to me under GSSoC, for making enhancement to the project.

![image](https://github.com/Yash-Parsana/CrazyCoderServerlessApi/assets/106910881/4c1fd0a1-bf01-4286-993b-30a20d180cf0)
👆 can add filter/ sorting options here.

**Comment by Yash-Parsana** [comment]
This feature is not required.
