### ISSUE TITLE
Login/Signup

### ISSUE THREAD

**Issue by mohakksingh** [Yash-Parsana/CrazyCoderServerlessApi#15]
i can add a sign - up page using MongoDB database. plz assign me this , I am a contributor under GSSoC 2024.

**Comment by soham0005** [comment]
Heyy @Yash-Parsana, can i work on authentication and authorization part under label gssoc?

**Comment by Vibhuti270** [comment]
i can solve this issue please assign me this , I am a contributor under GSSoC 2024.

**Comment by Yash-Parsana** [comment]
Authentication is not reqired. I want api should be open for all.
