### ISSUE TITLE
Route for Leetcode weekly and biWeekly contest

### ISSUE THREAD

**Issue by Subhash23jan** [Yash-Parsana/CrazyCoderServerlessApi#19]
I would like to work on this, 
Redirecting to leetcode contests, could you please assign this to me?

**Comment by Sathya-reddy1658** [comment]
I have  been working on routing lately so I could solve this issue with perfection, please assign me this task

**Comment by Yash-Parsana** [comment]
@Subhash23jan Could you please provide a detailed description of feature you want to implement?

**Comment by Subhash23jan** [comment]
/:username/contest   ->Get details about the user's contest participation.
@Yash-Parsana 
Also, i can  make routes which redirect to leetcode weekly and biweekly contests
Also, i can make route for leetcode daily problem

**Comment by Yash-Parsana** [comment]
@Subhash23jan All these features you have listed above is not needed.
