### ISSUE TITLE
Route for contest schedule of coding ninjas 

### ISSUE THREAD

**Issue by GbCderr14** [Yash-Parsana/CrazyCoderServerlessApi#24]
I would like to add scraping feature for scraping the schedules for contest of coding ninjas

**Comment by Yash-Parsana** [comment]
@GbCderr14 Can you describe the approach how you will do it?

**Comment by Yash-Parsana** [comment]
This issue is open for everyone if @GbCderr14 don't want to work on it.

**Comment by kart2004** [comment]
Hi @Yash-Parsana, Can I work on this feature ?
Thanks
