### ISSUE TITLE
Features idea : we can make a friendly contest api (1v1)

### ISSUE THREAD

**Issue by Phinix-BI** [Yash-Parsana/CrazyCoderServerlessApi#25]
@Yash-Parsana where we can add I'd of 2 or more people we create a code room 
Where we can select questions and the questions are show with the choosen 
Platform and set a time . And after time period we can fetch the details. 
And show the winner.

**Comment by Yash-Parsana** [comment]
@Phinix-BI  thank you for suggesting this feature but it is not needed.
