### ISSUE TITLE
Fix Signup and Signin Functionality and Implement Redirect to Homepage

### ISSUE THREAD

**Issue by vinay02103** [Yash-Parsana/CrazyCoderServerlessApi#26]
@Yash-Parsana 
Issue:
The current implementation of the signup and signin functionality on our platform is encountering issues, preventing users from successfully registering and logging in. This hampers user experience and obstructs access to our services.
Proposed Solution:
I propose to address this issue by thoroughly investigating the root cause and implementing necessary fixes to ensure seamless signup and signin experiences for our users. Additionally, upon successful login, users should be redirected to the homepage to enhance user engagement and navigation.
I would like to work on this issue and contribute to the rapid solution. Apart from my expertise in session management debugging and user authentication, I have written both frontend and backend programs.

**Comment by Abhinav-Sharma06** [comment]
Hi @vinay02103
I have worked on jwt tokens and more to get a strong a hold of authentication and authorization for sign up and log in functionality and I am willing to work on this issue so please assign me this task.

**Comment by Yash-Parsana** [comment]
I will suggest you all first go through code how things are working, BTW Authentication is not handled by this repo.
