### ISSUE TITLE
NavBar Missing 

### ISSUE THREAD

**Issue by rahul1841** [Yash-Parsana/CrazyCoderServerlessApi#31]
I can navbar in the project and also add links of social media so that user can go and follow you on social media.
Moreover i can improve navbar and can add dark mode feature

**Comment by Yash-Parsana** [comment]
@rahul1841 This is backend repo, how you will add nav bar here. visite this for web app: https://github.com/Yash-Parsana/CrazyCoderWebApp

I suggest you to first go through code and then raise issue.
