### ISSUE TITLE
FEATURE: LOGIN/Sign-Up USING GOOGLE

### ISSUE THREAD

**Issue by Manishak798** [Yash-Parsana/CrazyCoderServerlessApi#32]
Giving users an ease to login with there gmail in our web app will make UX better. One can achieve this using firebase oauth service of google to login or sign up.

I am a **MENTOR** in **GSSOC'24** raising this issue for contributors to contribute.

**Comment by Jhonsnowwwwww** [comment]
@Manishak798 hope u are doing good ,i can do this task please assign me i can easily implement login signup using google through firebase.

**Comment by Manishak798** [comment]
> @Manishak798 hope u are doing good ,i can do this task please assign me i can easily implement login signup using google through firebase.

As I said I am a Mentor so I can't assign issues to you only PA can take the final call on this.

**Comment by Manishak798** [comment]
@Yash-Parsana kindly look into this

**Comment by Yash-Parsana** [comment]
This is backend repo this purely focus on data fetchig you can find web app repo [here](https://github.com/Yash-Parsana/CrazyCoderWebApp). we are already using oauth in web and android app.
