### ISSUE TITLE
Year neads to be update dynamic in footer

### ISSUE THREAD

**Issue by kapilG0** [Yash-Parsana/CrazyCoderServerlessApi#34]
Year need to update dynamic 
![Screenshot_20240516_110323](https://github.com/Yash-Parsana/CrazyCoderServerlessApi/assets/59639410/17616c5d-1b34-4169-8e66-20e9b290deae)

**Comment by kapilG0** [comment]
Hello @Yash-Parsana please assign this issue to me under gssoc 24

**Comment by Yash-Parsana** [comment]
@kapilG0 We are not accepting contribution for that site.
