### ISSUE TITLE
Adding Onboarding Screens

### ISSUE THREAD

**Issue by Gresey** [Yash-Parsana/CrazyCoderServerlessApi#37]
Onboarding Screens for New Users

Description:

I will add onboarding screens to the CrazyCoder app to enhance the user experience for new users. The onboarding process will provide a brief and clear introduction to the app’s features and benefits, helping users understand how to make the most out of the app. This feature is crucial as it sets the first impression and ensures that users are well-informed about the app’s capabilities from the start.

Purpose:

The onboarding screens will serve to:

1. Introduce new users to CrazyCoder and its purpose.
2. Highlight the key features and functionalities of the app.
3. Guide users through the initial setup and permissions required for the best experience.
4. Promote user engagement and retention by making users feel welcomed and informed.

Content for Onboarding Screens:

1. Welcome Screen:
   - Brief introduction to CrazyCoder.
   - Message: "Welcome to CrazyCoder - Your Ultimate Companion for Competitive Programming!"

2. Feature Highlights:
   - Overview of the app’s main features.
   - Messages:
     - "Stay Updated with All Coding Contests and Hackathons Across Multiple Platforms."
     - "Set Reminders, Never Miss a Contest!"
     - "Compare Ranks with Friends and Engage in Healthy Competition with Leaderboards."

3. Interview Preparation:
   - Highlight the SDE section for interview prep.
   - Message: "Prepare for Interviews with Content Recommended by MAANG Employees."

4. User Interaction:
   - Explain the social features.
   - Messages:
     - "Chat with Friends and Discuss Strategies."
     - "Track Your Progress and Visit Profile Pages Directly from the App."

5. Getting Started:
   - Guide users on how to start using the app.
   - Message: "Let’s Get Started! Set Up Your Profile and Explore CrazyCoder."

Steps to Implement:

1. Design the onboarding screens with appealing visuals and concise text.
2. Integrate the screens into the app’s launch sequence for new users.
3. Ensure the onboarding can be skipped or revisited from the settings menu.
4. Collect user feedback on the onboarding process to make improvements.

Expected Outcome:

New users will have a smooth introduction to CrazyCoder, leading to higher user satisfaction, better engagement, and increased retention rates.

.

**Comment by Yash-Parsana** [comment]
@Gresey This is the backend repo don't raise android issue/feature here.
