### ISSUE TITLE
Go to home page on Clicking at Crazy Coder

### ISSUE THREAD

**Issue by kesharwaniyanshi** [Yash-Parsana/CrazyCoderServerlessApi#50]
We can add feature of accessing the home page even on clicking Crazy Coder .Currently only on clicking on logo we can go to home page.
![image](https://github.com/Yash-Parsana/CrazyCoderServerlessApi/assets/123561974/80c60c85-3fd7-4d77-8d83-54a4b7fa7a86)

**Comment by DarkAngelu** [comment]
Can you kindly assign this issue to me under GSSOC 2024?

**Comment by imvish21** [comment]
Can you please assign me this issue?

**Comment by Yash-Parsana** [comment]
This is backend repo
