### ISSUE TITLE
Website animations

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [Yash-Parsana/CrazyCoderServerlessApi#8]
Hi there, I am Ram👋
Give me the website work so i can add some animations in the website 
which looks good and attractive.
Librery to be used
-ityped.js
-aos.js

**Comment by Sathya-reddy1658** [comment]
i can integrate GSAP locomotive.js and other good looking animations into this , assign me this

**Comment by Yash-Parsana** [comment]
This is backend repo you can not add animation here checkout CrazyCoderWebApp
