### ISSUE TITLE
Authentication Enhancement

### ISSUE THREAD

**Issue by Ja3mamtora** [Yash-Parsana/CrazyCoderServerlessApi#9]
As i went through the deployment link register and login are not working as there backend services are not there, This side Jatin here am a backend developer working with Node.js from past 3 years would like to add REST API's for authentication purpose.

**Comment by CS251000** [comment]
Request for assignment of this issue to me.
I have an experience in working with this type of backend services and believe that I would be able to solve this issue to the best of my abilities

**Comment by tusharyadav11** [comment]
would like to work on this functionality. in my earlier projects i have worked on this functionality. I would be grateful if you could assign me this functionality

**Comment by Yash-Parsana** [comment]
We want to keep this api open for all no need of authentication.
